# Computation on numpy arrays
* comutation on numpy  arrays can be very fast or it can be very slow
* the key to makingit fast is to use 

In [17]:
import numpy as np
x=np.array([1,2,3,4])
y=np.array([4,5,6,5])
xy=np.add(x,y)
print(xy)

[5 7 9 9]


In [18]:
x=np.array([1,2,3,4])
y=np.array([4,5,6,5])
xy=np.subtract(x,y)
print(xy)

[-3 -3 -3 -1]


In [19]:
x=np.array([1,2,3,4])
y=np.array([4,5,6,5])
xy=np.multiply(x,y)
print(xy)

[ 4 10 18 20]


In [20]:
x=np.array([1,2,3,4])
y=np.array([4,5,6,5])
xy=np.divide(x,y)
print(xy)

[0.25 0.4  0.5  0.8 ]


In [21]:
x=np.array([1,2,3,-1,-4,3])
np.absolute(x)
np.exp(x)
np.exp2(x)
np.log(x)
np.log2(x)


C:\Users\nmaha\AppData\Local\Temp\ipykernel_36432\3249483971.py:5: RuntimeWarning: invalid value encountered in log
  np.log(x)
C:\Users\nmaha\AppData\Local\Temp\ipykernel_36432\3249483971.py:6: RuntimeWarning: invalid value encountered in log2
  np.log2(x)


array([0.       , 1.       , 1.5849625,       nan,       nan, 1.5849625])

# Advance Ufunction Features

In [22]:
x=np.arange(2,20,2)
print(x)
z=np.empty(9)
print(z)
print(np.multiply(x,10,out=z))

[ 2  4  6  8 10 12 14 16 18]
[ 20.  40.  60.  80. 100. 120. 140. 160. 180.]
[ 20.  40.  60.  80. 100. 120. 140. 160. 180.]


# 2.Aggregations(reduce method)
* if you like to reduce an array with particular operation we can use the reduce method of any ufucn
* A reduce repeatetly appiles a given operation to the elememt of array untill only a single result remains

In [23]:
x=np.arange(1,11)
print(x)
np.add.reduce(x)

[ 1  2  3  4  5  6  7  8  9 10]


np.int64(55)

In [24]:
x=np.arange(1,11)
print(x)
np.add.accumulate(x)

[ 1  2  3  4  5  6  7  8  9 10]


array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [25]:
x=np.arange(1,11)
print(x)
np.cumsum(x)

[ 1  2  3  4  5  6  7  8  9 10]


array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [26]:
np.min(x)

np.int64(1)

In [27]:
np.max(x)

np.int64(10)

In [28]:
import numpy as np 
x=np.array([34,2,45,3,2,89,5])
np.sort(x,descending=True)

array([89, 45, 34,  5,  3,  2,  2])

In [30]:
x=np.array([1,2,3,4,5])
f=[True,False,True,True,False]
x[f]

array([1, 3, 4])

In [31]:
f=x%2==0
x[f]

array([2, 4])