NumPy stands for Numerical Python.

It is a popular Python library used for numerical and mathematical operations, especially with arrays and matrices

numpy is one of the most importand fondation package for numerical computing in python 
it is an open source python package that is widely use in scince and enigernnering
numpy libary contains multidimensional array data structure sach as homogenous, an demision anti-array and a large libary of fuction that operate efficently of these data structure.


# why do we use python numpy
* we use python numpy array instead of list because of the below there reasons
> - less memory
> - fast
> - conveint to understand
> - vectoriesation(way d=faster the loop and list)

# why not pyhton inbuilt data structure list.
* A python list stores elements plus meta data plus pointers 
- > that's is uses more memory
* a numpy array stores data in an countious blocks 
- > more compact and efficent

# what is the diffrence between array and list 
* LIST
- > List is a built-in Python data structure.
- >It can store different data types.
- >It is generally slower for numerical calculations.
- >It uses more memory.
* ARRAY
- >NumPy array is provided by the NumPy library.
- > It usually stores elements of the same data type.
- > It is faster for numerical calculations.
- > It uses less memory.

In [5]:
import numpy as np
np.array=[1,2,3,3]
print(type(np))

<class 'module'>


In [2]:
import numpy as np

CHECKING NUMPY VERSION 

In [4]:

np.__version__

'2.5.2'

In [5]:
#convert list into array 
arr=np.array((1,2,3,4))
print(arr)

[1 2 3 4]


In [6]:
#convert dictionary in array
dict={'a':1,'b':2,'c':3}
arr1=np.array(list(dict.items()))
print(arr1)

[['a' '1']
 ['b' '2']
 ['c' '3']]


In [7]:
oneD=np.array([1,2,3,4,5])
print(oneD)
 #arrtributes of array
print("Shape:", oneD.shape)#dimension of array
print("Data Type:", oneD.dtype)#data type of array  
print("Size:", oneD.size)#size of array
print("Item Size:", oneD.itemsize)#size of each item in array
print("Number of Dimensions:", oneD.ndim)#number of dimensions of array
print("Array Type:", type(oneD))#type of array
print

[1 2 3 4 5]
Shape: (5,)
Data Type: int64
Size: 5
Item Size: 8
Number of Dimensions: 1
Array Type: <class 'numpy.ndarray'>


<function print(*args, sep=' ', end='\n', file=None, flush=False)>

In [9]:
#creating 2D array
twoD=np.array([[1,2,3],[4,5,6]])
print(twoD)
print("Shape:", twoD.shape)#dimension of array
print("Data Type:", twoD.dtype)#data type of array
print("Size:", twoD.size)#size of array
print("Item Size:", twoD.itemsize)#size of each item in array

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Data Type: int64
Size: 6
Item Size: 8


In [10]:
#creating 3D array
threeD=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(threeD)
print("Shape:", threeD.shape)#dimension of array
print("Data Type:", threeD.dtype)#data type of array    
print("Size:", threeD.size)#size of array
print("Item Size:", threeD.itemsize)#size of each item in array

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)
Data Type: int64
Size: 12
Item Size: 8


# creating array from functions 

In [12]:
x=np.zeros((3,3),dtype=int)
print(x)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [7]:
#vetor addtion 
a=np.array([1,2,3])
b=np.array([5,6,7])
print(a+b)

[ 6  8 10]


In [9]:
import time

In [10]:
arr=np.arange(10000)
list=[x for x in range(10000)]
#python list
start=time.time()
list2=[x*2 for x in list]
end=time.time()
print(end-start)

0.000728607177734375


# broadcasting 
* operation between diffrent shape arrray
* Numpy automattically expands the smaller array(without copying) so shapers become compatible

In [11]:
a=np.array([1,2,3,4])
b=5 #scaler
#here 5 is broadcast to [5,5,5]
print(a+b)

[6 7 8 9]


In [ ]:
arr=np.array([1,2,3]) #shape(1,3)
vec=np.array([[1],[2],[3]])
print(arr+vec)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


# How to use pyhton numpy to generate random numbers

In [ ]:
np.random.rand()
#generate random numbers from 0 to 1of a give size

In [15]:

s=np.random.rand(10)
print(s)

[0.09457968 0.86239023 0.67815107 0.08110793 0.22117109 0.24817686
 0.14278902 0.43327214 0.13223906 0.90658603]


In [ ]:
rng=np.random.default_rng()
s-rng.random.rand(3,40)
print(s)

TypeError: Cannot interpret '40' as a data type

# 3. THE CHOICE() METHOD
* Generate random number from the array


In [3]:
x=np.random.choice([1,2,3,4,5])
print(x)

1


In [6]:
x=np.random.choice([1,2,3,4,5,6,7,8], size=(2,3))
print(x)

[[3 8 1]
 [6 7 7]]


# indexing in numpy is quite similar to python"s list standard indexing

In [7]:
x=np.array([19,10,23,45])
x[2]

np.int64(23)

In [8]:
x=np.array([19,10,23,45])
x[0:2]

array([19, 10])

In [18]:
y=np.array([[19,10,23],[2,3,4]])
y[0,2]

np.int64(23)

In [19]:
y=np.array([[19,10,23],[2,3,4]])
y[0:2]

array([[19, 10, 23],
       [ 2,  3,  4]])

In [20]:
x=np.array([10,23,45,67,89])
x[1:4]

array([23, 45, 67])

In [ ]:
y=np.array([[12,23,34],[2,4,67],[1,1,1],[2,2,2]])
y[1:2]

array([[12, 23, 34],
       [ 2,  4, 67]])

In [26]:
y=np.array([[12,23,34],[2,4,67],[1,1,1],[2,2,2]])
y[-1:]

array([[2, 2, 2]])

In [30]:
y=np.array([[12,23,34],[2,4,67],[1,1,1],[2,2,2]])
y[-3:2]

array([[ 2,  4, 67]])

In [ ]:
y=np.array([[12,23,34],[2,4,67],[1,1,1],[2,2,2]])
y[:,1:]

array([[ 4, 67],
       [ 1,  1],
       [ 2,  2]])

In [35]:
y=np.array([[12,23,34],[2,4,67],[1,1,1],[2,2,2]])
y[0:,1:2]

array([[23],
       [ 4],
       [ 1],
       [ 2]])

In [36]:
arr=np.array([1,2,3,4])
s=arr[1:3]
s[0]=100
print(arr)
print(s)
print(s.base)

[  1 100   3   4]
[100   3]
[  1 100   3   4]


In [3]:
x=np.array([12,15,24,13,25,55,45])
x[x%5==0]

array([15, 25, 55, 45])

# FANCY INDEXING
fancy indexing is like the simple indexing we've already seen,but we pass arrrays of indices in place of single sclars

In [ ]:
arr=np.random.randint(2,100,size=(10,10))
xy=np.random.rand(10,10)
print(arr)
print(xy)
print(xy[1,3])
print(xy[2,7])

[[37 29 49 15 38 58 93 10 62 25]
 [ 8 88 78  9 84 50 95 20 16  5]
 [75 13 36 23 75  4 74 10  4 48]
 [35 89 47 54 55 33 30 76 60 96]
 [47 42 64 20 28 87  8 26 39 53]
 [83 40 23 71  6 79 65 69  5 80]
 [62 44 95 64 71  4 46 48 95 37]
 [60 19 80 62 46 26 99 76 10 73]
 [55 48  9 66 89 55 47  6 72 30]
 [89 55 24 85 87 36 40 92  8 41]]
[[0.35496065 0.19996268 0.79497353 0.96980907 0.03473623 0.31555388
  0.5388589  0.54804753 0.48108585 0.9714548 ]
 [0.96915235 0.8301685  0.43319266 0.9749645  0.41160498 0.30349534
  0.85451802 0.91945416 0.18672458 0.91948654]
 [0.87813245 0.73385816 0.99952083 0.56221327 0.08176829 0.18089454
  0.12009833 0.92512486 0.48327561 0.42762175]
 [0.13813601 0.25098298 0.60902317 0.52419378 0.20470468 0.6808494
  0.65959711 0.33419201 0.59461796 0.19673591]
 [0.63436321 0.51705479 0.86030043 0.32291637 0.7659653  0.56826958
  0.45621687 0.17125443 0.36749527 0.90597748]
 [0.61245157 0.64967543 0.84805541 0.89130446 0.64620781 0.1450505
  0.59451828 0.97046345 0.71

In [14]:
arr[:,[1,3,5]]

array([[29, 15, 58],
       [88,  9, 50],
       [13, 23,  4],
       [89, 54, 33],
       [42, 20, 87],
       [40, 71, 79],
       [44, 64,  4],
       [19, 62, 26],
       [48, 66, 55],
       [55, 85, 36]], dtype=int32)

# check if returns a copy or view 


In [1]:
import numpy as np
n=np.arange(1,10)
n[5]=20
print(n)
id(n)

[ 1  2  3  4  5 20  7  8  9]


1817280216880

In [2]:
y=n.reshape((3,3)).base
print(y)
id(y)

[ 1  2  3  4  5 20  7  8  9]


1817280216880

# Check if array owns its data
* As mentioned above,copies owns the data,and views does not own the data,but how can we check this?

. Every Numpy array has the attribute base that returns None if the array owns the data otherwise,the base attribute refers to the orignal
object


In [5]:



x=np.random.randint(10, size=(2,3))
print(x)
x.reshape(-1)


[[9 7 4]
 [4 7 8]]


array([9, 7, 4, 4, 7, 8], dtype=int32)

In [6]:

x=np.arange(1,10).reshape((3,3))
print(x)
x.T




[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# Rotation of Array
> - the rot90() function is used to rotate an array by 90 degrees in the plane specified by axes
> - Syntax:
    *  numpy.rot90(m,k=1,axes=(0,1))

In [7]:
import numpy as np

x = np.array([[1,1,1],
              [2,2,2]])

y = np.array([[4,4,4],
              [3,3,3]])

result = np.concatenate([x, y], axis=0)

print(result)

[[1 1 1]
 [2 2 2]
 [4 4 4]
 [3 3 3]]


In [8]:
x=np.array([[1,1,1],[2,2,2],[3,3,3]])
y=np.array([[4,4,4],[5,5,5]])
np.vstack([x,y])

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]])

In [9]:
x=np.array([[1,1,1],[2,2,2]])
y=np.array([[3,3,3],[4,4,4]])
np.hstack([x,y])

array([[1, 1, 1, 3, 3, 3],
       [2, 2, 2, 4, 4, 4]])

# Spliting of array 
* the returrn value of split() method is an array containing each of the split as an array

In [10]:
x=np.arange(1,13)
print(x)
np.split(x,4)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [ ]:
#split [0:3] , [3:5] ,[5:7],[7:]
x=np.arange(1,10)
print(x)
np.split(x,[3,5,7])

[1 2 3 4 5 6 7 8 9]


[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [12]:
x=np.arange(1,10).reshape([3,3])
print(x)
np.hsplit(x,3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [13]:
x=np.arange(1,11).reshape([2,5])
print(x)
np.hsplit(x,[1,2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


[array([[1],
        [6]]),
 array([[2],
        [7]]),
 array([[ 3,  4,  5],
        [ 8,  9, 10]])]

In [16]:
x=np.arange(1,11).reshape([5,2])
print(x)
np.vsplit(x,[3])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


[array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[ 7,  8],
        [ 9, 10]])]

In [20]:
x=np.array([1,2,3,4,])
print(x.dtype)
y=x.astype(np.float64)
print(y.dtype)
print(x,y)

int64
float64
[1 2 3 4] [1. 2. 3. 4.]


In [23]:
x=np.array([1,2,3,4,3,4,5.3])
print(x.dtype)
y=x.astype(np.int32)
print(y.dtype)
print(x,y)

float64
int32
[1.  2.  3.  4.  3.  4.  5.3] [1 2 3 4 3 4 5]


In [25]:
x=np.array(['5.9','23.4','4.5'],dtype=str)
y=x.astype(np.float64)
print(y.dtype)
print(y)

float64
[ 5.9 23.4  4.5]
