NumPy stands for Numerical Python.

It is a popular Python library used for numerical and mathematical operations, especially with arrays and matrices

numpy is one of the most importand fondation package for numerical computing in python 
it is an open source python package that is widely use in scince and enigernnering
numpy libary contains multidimensional array data structure sach as homogenous, an demision anti-array and a large libary of fuction that operate efficently of these data structure.


# why do we use python numpy
* we use python numpy array instead of list because of the below there reasons
> - less memory
> - fast
> - conveint to understand
> - vectoriesation(way d=faster the loop and list)

# why not pyhton inbuilt data structure list.
* A python list stores elements plus meta data plus pointers 
- > that's is uses more memory
* a numpy array stores data in an countious blocks 
- > more compact and efficent

# what is the diffrence between array and list 
* LIST
- > List is a built-in Python data structure.
- >It can store different data types.
- >It is generally slower for numerical calculations.
- >It uses more memory.
* ARRAY
- >NumPy array is provided by the NumPy library.
- > It usually stores elements of the same data type.
- > It is faster for numerical calculations.
- > It uses less memory.

In [5]:
import numpy as np
np.array=[1,2,3,3]
print(type(np))

<class 'module'>


In [2]:
import numpy as np

CHECKING NUMPY VERSION 

In [4]:

np.__version__

'2.5.2'

In [5]:
#convert list into array 
arr=np.array((1,2,3,4))
print(arr)

[1 2 3 4]


In [6]:
#convert dictionary in array
dict={'a':1,'b':2,'c':3}
arr1=np.array(list(dict.items()))
print(arr1)

[['a' '1']
 ['b' '2']
 ['c' '3']]


In [7]:
oneD=np.array([1,2,3,4,5])
print(oneD)
 #arrtributes of array
print("Shape:", oneD.shape)#dimension of array
print("Data Type:", oneD.dtype)#data type of array  
print("Size:", oneD.size)#size of array
print("Item Size:", oneD.itemsize)#size of each item in array
print("Number of Dimensions:", oneD.ndim)#number of dimensions of array
print("Array Type:", type(oneD))#type of array
print

[1 2 3 4 5]
Shape: (5,)
Data Type: int64
Size: 5
Item Size: 8
Number of Dimensions: 1
Array Type: <class 'numpy.ndarray'>


<function print(*args, sep=' ', end='\n', file=None, flush=False)>

In [9]:
#creating 2D array
twoD=np.array([[1,2,3],[4,5,6]])
print(twoD)
print("Shape:", twoD.shape)#dimension of array
print("Data Type:", twoD.dtype)#data type of array
print("Size:", twoD.size)#size of array
print("Item Size:", twoD.itemsize)#size of each item in array

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Data Type: int64
Size: 6
Item Size: 8


In [10]:
#creating 3D array
threeD=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(threeD)
print("Shape:", threeD.shape)#dimension of array
print("Data Type:", threeD.dtype)#data type of array    
print("Size:", threeD.size)#size of array
print("Item Size:", threeD.itemsize)#size of each item in array

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)
Data Type: int64
Size: 12
Item Size: 8


# creating array from functions 

In [12]:
x=np.zeros((3,3),dtype=int)
print(x)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [7]:
#vetor addtion 
a=np.array([1,2,3])
b=np.array([5,6,7])
print(a+b)

[ 6  8 10]


In [9]:
import time

In [10]:
arr=np.arange(10000)
list=[x for x in range(10000)]
#python list
start=time.time()
list2=[x*2 for x in list]
end=time.time()
print(end-start)

0.000728607177734375


# broadcasting 
* operation between diffrent shape arrray
* Numpy automattically expands the smaller array(without copying) so shapers become compatible

In [11]:
a=np.array([1,2,3,4])
b=5 #scaler
#here 5 is broadcast to [5,5,5]
print(a+b)

[6 7 8 9]


In [ ]:
arr=np.array([1,2,3]) #shape(1,3)
vec=np.array([[1],[2],[3]])
print(arr+vec)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


# How to use pyhton numpy to generate random numbers

In [ ]:
np.random.rand()
#generate random numbers from 0 to 1of a give size

In [15]:

s=np.random.rand(10)
print(s)

[0.09457968 0.86239023 0.67815107 0.08110793 0.22117109 0.24817686
 0.14278902 0.43327214 0.13223906 0.90658603]


In [ ]:
rng=np.random.default_rng()
s-rng.random.rand(3,40)
print(s)

TypeError: Cannot interpret '40' as a data type